[workspace]
members = ["crates/*"]

[workspace.package]
authors = ["Romain TRUCHI"]
edition = "2021"

[workspace.dependencies]

[profile.dev]
# Remove debug stuff in the binary
debug = false
strip = true
